version: '3.8'
services:
  server:
    build:
      context: ./online_inference
      dockerfile: Dockerfile
    command:  uvicorn api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000 
    volumes:
      - ./online_inference/:/online_inference/
    ports:
      - 8000:8000
    restart: always

    healthcheck:
      test: [ "CMD-SHELL"]
      interval: 5s
      timeout: 5s
      retries: 5